# 9. 자바 예외 처리

## 1. 자바에서의 에러와 예외

자바에서는 프로그램 동작 중 발생하는 오작동이나, 비정상적인 종료 상황을 에러와 예외(Exception)으로 나누어 다룬다. <br>
`Error`는 보통 프로그램 코드에 의해 복구할 수 없는 심각한 오류를 나타낸다. <br>
예를 들어 JVM이 자원이 부족하거나, 불변식이 꺠지는 상황 등에서 사용된다. (ex OutOfMemoryError, StackOverflowError) <br>
그리고 예외인 `Exception`은 보통 프로그램 코드에 의해 수습될 수 있는 오류를 나타낸다. <br> 

![1  예외 클래스 계층도](https://github.com/binary-ho/TIL-public/assets/71186266/2369168b-263a-40b4-a0c9-91b34355b422)

<br>

위 그림과 같이 자바에선 이런 상황들을 `Throwable`이라는 인터페이스를 구현한 `Error`와 `Exception`으로 구분한다. <br> 


### 2. Exception의 분류 
이러한 Exception은 검사 여부에 따라 검사 예외 (Checked Exception)과 비검사 예외(Unchecked Exception)로 나눌 수 있다.

![checked unchecked](https://github.com/binary-ho/TIL-public/assets/71186266/44c9371b-1f14-42d1-b150-24a865fb6a20)

검사 예외는 말 그대로, 예외 상황에 대해 인지하고 대응하는 것을(검사) 강제한다. <Br>
Exception의 하위 분류 중, Runtime에서 발생하는 비검사 예외를 RuntimeException이라고 부른다. <Br> <br> 

RuntimeException의 대부분은 API 호출부에서 "약속", "전재조건"을 지키지 않거나 못하는 경우 발생한다. <br>
예를 들어, 회원가입시 비밀번호의 형식을 맞추지 않았다던지, 이미 가입한 이메일로 회원가입 신청을 한다던지, 있지도 않은 상품을 구매하려 시도한다던지 등의 사유인데. <br>
입력으로써 위 세가지 경우에 대한 요청이 들어온다면, 프로그램을 짜는 사람은 그런 가능성을 인지하고, 대응해 줘야 할 것이다. <Br>
분명 서비스에선 비밀번호는 정해진 양식이 있다거나, 이미 가입한 이메일로는 가입할 수 없다고 알려줬을것인데, 요청이 온 것이다 <br>
사람은 문에 달린 "미시오" "당기시오" 조차 제대로 읽지 않는다. <br>
사람은 불완전한 존재이기 때문에 이런 가능성을 예상하고 방지하는 것은 중요하다. <Br>
**프로그래머의 번거로움이 사용자의 편안함을 가져온다.** <br> <br>

이러한 오동작들을 발생 시점에 따라 구분하면 아래와 같이 나누어 볼 수 있다.
1. 컴파일 에러 : 컴파일시 컴파일러가 검사를 수행해 발견하는 에러
2. 런타임 에러 : 프로그램 실행중 발생하는 에러.
3. 논리적 에러 : 프로그램 자체는 컴파일 잘 되고, 잘 돌아가지만, 의도한 것과 다르게 동작하는 에러 

## 3. 예외 선택의 기준

다양한 Exception의 분류 안에서 언제 어떤 예외를 사용해야할지 헷갈릴 수 있다. <br>
그에 대한 지침으로써 이펙티브 자바에서는 `복구할 수 있는 상황에서는 검사 예외를, 프로그래밍 오류에는 런타임 예외를 사용하라`고 원하고 있다. <br>
그 이외에도 다양한 지침들이 있다. 아래 링크의 글을 참고하라. <br>

[Item 70. 복구할 수 있는 상황에는 검사 예외를, 프로그래밍 오류에는 런타임 예외를 사용하라](https://github.com/binary-ho/TIL-public/blob/main/Effective%20Java/Item%2070.%20%EB%B3%B5%EA%B5%AC%ED%95%A0%20%EC%88%98%20%EC%9E%88%EB%8A%94%20%EC%83%81%ED%99%A9%EC%97%90%EB%8A%94%20%EA%B2%80%EC%82%AC%20%EC%98%88%EC%99%B8%EB%A5%BC%2C%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%20%EC%98%A4%EB%A5%98%EC%97%90%EB%8A%94%20%EB%9F%B0%ED%83%80%EC%9E%84%20%EC%98%88%EC%99%B8%EB%A5%BC%20%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC.md)

# 4. Java Exception Handling
## 4.1 try-catch 문법을 통해 예외를 처리할 수 있다
예외가 발생하는 경우를 try-catch 문법을 통해 대응할 수 있다. <br>
이는 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하기 위함이 목표다.

![image](https://github.com/binary-ho/TIL-public/assets/71186266/78507d43-73c3-4f76-85b3-8ef88b3d0fc6)

`throw`를 사용하면 특정 예외를 직접 발생시킬 수가 있다. <br>
원래대로라면 예외가 발생하는 겨웅 프로그램 실행이 종료되어야 하나,  <br>
`try` 에서 예외가 발생했는데도 종료되지 않고 `catch` 블록의 로직이 수행되었다. <br> <br>

기본적으로 예외가 발생한다면 **예외 클래스의 인스턴스가 새로 만들어진다.** <Br> 
위의 사진과 같이 직접 예외를 발생시켜 줄때 `new RuntimeException()`과 같이 런타임 Exception의 예외 인스턴스를 직접 만드는 이유가 이것이다. <br>
(참고로 커스텀 예외를 만들 때는 매번 예외 인스턴스를 만드는 비용을 아끼기 위해 내부적으로 public 인스턴스 상수를 운용하고 생성자를 막는 것을 추천) <br> <br>

catch문은 하나의 try 블록 아래에 여러개를 만들 수도 있는데, <br>
만약 예외가 발생한 곳이 try 블럭 안이라면 처리할 수 있는 catch를 위 부터 아래로 순회한다. <br>
instanceof의 결과가 true가 나올 떄까지 발생 예외 인스턴스와 catch문의 괄호 안의 클래스를 비교한다 <br>
instanceof의 결과가 true가 나온 경우 안의 로직을 실행한다. <Br> <br>

프로그램의 흐름이 바뀌는데, try 블록 안에서 예외가 발생한 이후의 로직들은 무시된다. 

![4  예외 아래는 실행되지 않고, catch문 거친 다음 빠져나간다](https://github.com/binary-ho/TIL-public/assets/71186266/e607585b-b137-41a2-81f8-4d4bed1e3b2e)

위의 그림은 예외 발생 이후 로직이 진행된다면 실패하도록 만든 테스트이다. <br>
성공하는 모습을 볼 수 있다. <br>

![5  unreachable](https://github.com/binary-ho/TIL-public/assets/71186266/bccc79e2-6f9d-438a-8453-3ab806f26fe3)

<br>

애초에 이렇게 대놓고 예외를 발생시키면, 예외의 아래는 컴파일러가 닿을 수 없는 곳이라고 알려준다.

<br> <br>

[문법 활용 참고]

1. try-catch문 안에 try-catch을 중첩해 적을 수 있다.
2. try-catch 블럭도 블럭이기 떄문에 이 안에서 선언된 변수와는 블럭 안에서만 유효하다
3. catch문 앞 괄호에서 받은 Exception 또한 블럭 안에서만 유효하다.
4. OR 연산을 통해 한 catch문이 여러 예외를 catch할 수 있다. <br> 예 -> `catch (Ex1 | Ex2 e)` 이를 멀티 캐치라고 부른다.  


## 4.2 메서드 예외 선언
메서드에서 어떤 예외가 발생할 수도 있다고 선언할 수 있다. throws
이 메서드 안에 처리되지 않은 어떤 예외가 발생할 수 있는 가능성을 알리는 것으로,
이 메서드의 호출부에서 처리를 강제한다 <br>
다르게 생각해서 호출부에게 처리를 떠넘길 수도 있다. <br>
물론 이 경우 호출부에서 처리할 수 있는 예외 상황이 맞는지 신중하게 고려해야 하고, <Br>
아닌 경우 처리할 수 있는 정보를 제공해야 한다.

![image](https://github.com/binary-ho/TIL-public/assets/71186266/7662b514-f193-4293-8383-5ee475eb7f5f)

위 그림과 같이 핸들링 하지 않는 경우 컴파일 에러를 발생시킨다. <br>


## 4.3 `finally` 블럭
예외 발생 여부와 상관없이 무조건 실행해야 하는 로직들이 있을 수 있다. <Br>
이를 `finally`를 이용해 구현할 수 있다.

![6  finally](https://github.com/binary-ho/TIL-public/assets/71186266/5664557c-72a7-4f96-b731-e957b7e04acb)

try 블럭이 그냥 끝나던, 예외가 발생해 catch로 넘어가던 <br>
finally 블럭의 내용은 무조건 실행된다. <br>

위 그림에서 첫 try-catch에선 예외가 발생하지 않았고, 두 번째 try-catch에선 발생했다. <br>
예외가 발생했던 안 했던 위와 같이 finally 블럭 안에 있는 로직이 실행됐다. -> finally1, 2 라는 메시지를 출력했다.

## 4.4 자동 자원 반환 `try-with-resources`

Java 7에서 더해진 try-catch문의 변형으로, <br>
반환이 필요한 자원을 강제로 반환하는 것을 돕는다. <br>

![image](https://github.com/binary-ho/TIL-public/assets/71186266/3d2778d7-1121-41ce-bfcc-86c48cca2232)

위와 같이 try문 앞에 괄호가 생겼다. <br>
사용하고, 자동으로 반환할 자원을 괄호 안에 정의하면 된다. <br> <br>

클래스 중엔 사용후 후처리가 필수인 클래스들이 있다. 특히 자바의 IO 관련 클래스에서 많이 필요로 되는데, <br>
원래라면 finally를 통해 반환할 수도 있겠지만, <Br>
finally에서 반환하는 로직에서 또 Exception이 발생한다면 어떻게 할 것인가? <Br> 
어쩔 수 없이 finally 안에  try-catch로 중첩해 처리해야 한다. <br> <br>

문제는 복잡하기도 복잡하지만, finally 에서 예외가 발생하는 경우 try 블럭의 예외는 무시된다. <br>
`try-with-resources`는 이런 부분을 간편하게 처리하기 위해 등장했다. <br>
괄호 안에 객체를 생성하는 문장을 넣으면, 해당 객체는 try 블럭 안에서만 사용할 수 있는데, <br>
따로 close를 호출하지 않아도, 괄호 안의 객체에 대해 자동적으로 close()가 호출된다!! <br> <br> 

물론 이러한 자동 close()를 위해선 당연히 특정 인터페이스의 구현이 필요한데 <br> 
java.lang의 AutoCloseable을 구현해야 한다 <br>


![AutoCloseable](https://github.com/binary-ho/TIL-public/assets/71186266/5d2cc413-8208-4625-b8bd-6e47d5d3e48c)

위 인터페이스를 구현한다면 안전하게 객체를 반환할 수 있다! <br>
이펙티브 자바 아이템 9에서도 try-finally 보다는 try-with-resources를 사용하라고 권한다 <br>
자세한 내용은 아래 링크를 확인하자. <br>

[Item 9. try-finally 보다는 try-with-resources를 사용하라](https://github.com/binary-ho/TIL-public/blob/main/Effective%20Java/Item%209.%20try-finally%20%EB%B3%B4%EB%8B%A4%EB%8A%94%20try-with-resources%EB%A5%BC%20%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC.md)

## 4.5 자바 커스텀 예외 만들기
Exception 혹은 RuntimeException 클래스를 상속 받아서 커스텀 예외를 만들 수 있다. <br>
상황에 맞게 상속 받아 하위 클래스로서 만들어 해당 예외의 한 종류로 만들면 되는데, 왜 필요할까? <br> <br>

프로젝트를 진행하다 보면, 자바에서 기본적으로 제공하지 않지만 우리 프로그램에서만 발생할 수 있는 특별한 예외 상황이 있을 수 있다. <br>
물론 이런 상황에서도 자바의 예외를 사용하는 것이 권해지지만, <br>
또 다른 이유로 커스텀 예외를 만드는 편이 났다. <Br>
결국 예외 상황을 클라이언트단에 알려서, 클라이언트 개발자가 상황을 보고 유저에게 적당한 행위를 요청할 수도 있다. <Br>
클라이언트단에 더 자세한 정보를 알리기 위해선 직접 만든 클래스를 사용하는 것이 좋다. <br> <br>

보통은 프로그램내에서 커스텀 예외 하나를 만든 다음, 구체적인 상황은 하위 클래스로 만들어서 
상위 클래스로 catch해서 사용하는 편이다. <br>

## Reference
- 자바의 정석 <남궁성 저>
- Effective Java 아이템 9, 70 <조슈아 블로크>
- [Exception In Java](https://interviewnoodle.com/exception-in-java-89a0b41e0c45)
